### ISSUE TITLE
Failed to load the omni-ruler package

### ISSUE THREAD

**Issue by yriveiro** [Problematic/omni-ruler#6]
[Enter steps to reproduce below:]
1. open atom in terminal

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [omni-ruler](https://github.com/Problematic/omni-ruler) package, v0.3.1
### Stack Trace

Failed to load the omni-ruler package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/yriveiro/.atom/packages/omni-ruler/lib/omni-ruler-view.coffee:4:199)
    at /Users/yriveiro/.atom/packages/omni-ruler/lib/omni-ruler-view.coffee:9:5
    at Object.<anonymous> (/Users/yriveiro/.atom/packages/omni-ruler/lib/omni-ruler-view.coffee:92:5)
    at Object.<anonymous> (/Users/yriveiro/.atom/packages/omni-ruler/lib/omni-ruler-view.coffee:94:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "emmet",
      "autocomplete",
      "go-plus",
      "Zen",
      "autocomplete-plus-async",
      "minimap",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "symbols-tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/yriveiro/Development/github"
  },
  "omni-ruler": {
    "columns": [
      80,
      90,
      120
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-cli-diff, v0.11.0
atom-html-preview, v0.1.6
atom-jshint, v1.5.0
atom-lint, v0.20.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
color-picker, v1.6.0
docblockr, v0.6.3
editor-stats, v0.17.0
file-icons, v1.5.3
filetype-color, v0.1.4
git-history, v2.3.0
git-log, v0.3.0
git-plus, v4.4.11
git-tab-status, v1.6.0
language-jade, v0.3.0
linter, v0.12.0
linter-php, v0.0.12
omni-ruler, v0.3.1
phpunit, v1.0.9
phpunit-snippets, v0.1.0
pretty-json, v0.3.2
script, v2.18.0
seti-syntax, v0.3.3
space-tab, v0.1.0
travis-ci-status, v0.13.0
vim-mode, v0.43.0
wakatime, v4.0.1
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by Problematic** [comment]
Package has been updated. Thanks for the report!
